### ISSUE TITLE
Change ChEBI name of cicloheximide to cycloheximide

### ISSUE THREAD

**Issue by robnash** [ebi-chebi/ChEBI#3127]
Hi,

Currently the CHEBI:27641 entry is listed with the name cicloheximide and has cycloheximide listed as a synonym. We had talked internally about this being confusing based on usage in the scientific community and this morning one of our users (SGD) wrote in suggesting this was an error. When I checked some other sites I find that they have this chemical listed as cycloheximide:

https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL123292
http://chem.sis.nlm.nih.gov/chemidplus/rn/66-81-9
http://www.genome.jp/dbget-bin/www_bget?cpd:C06685

Would it be possible to change the name based on usage?

Cheers,
Rob

**Comment by G-Owen** [comment]
Hi Rob,

Where they exist, we tend to use the International Nonproprietary Name for drugs, as these tend to be the most widely used - hence our use of cicloheximide, rather than cycloheximide (the US adopted name) . 
A problem with the latter is that is looks like a sensible 'structural' name for a chemical - possibly a synonym for piperidine 2,6-dione; possibly a synonym for azepine-2,7-dione based (see http://www.chemspider.com/Chemical-Structure.9599288.html for a "cyclohexamide" derivative), whereas there is no way of generating the structure of cicloheximide/cycloheximide from its name - a "look-up list" is required. 
However, a Google search reveals that in this case, usage of the USAN is vastly greater than that of the INN (>600,000 hits compared with 5,000, respectively). Accordingly, I have changed the display name of ChEBI:27641 to cycloheximide, while retaining cicloheximide as a synonym.

Best wishes for Christmas and the New Year.

Gareth
