### ISSUE TITLE
Chemical processes

### ISSUE THREAD

**Issue by pbuttigieg** [ebi-chebi/ChEBI#3152]
Hello,

Over at ENVO, we would like to make use of chemical process classes like "oxidation" for environmental processes like "wildfires". GO has classes, but these - naturally - are bound to biological processes. 

Would CHEBI consider creating such classes too or is there another OBO-aligned ontology we should import from?

Thanks!

**Comment by G-Owen** [comment]
Hi Pier,

ChEBI is really set up for handling entities that physically exist (e.g. oxidising agent), rather than terms that describe what occurs during events, etc. 

There are other ontologies that handle chemical processes, including the Molecular Process Ontology (MOP), the Physico-Chemical Process Ontology (REX) and the Name Reaction Ontology (RXNO - although this concentrates on chemical reactions that are best known by the names of the researchers who first describe the particular reaction) . The Chemical Methods Ontology (CHMO) may also be of use.

Have you tried [AberOwl](http://aber-owl.net/) or the [Ontology Lookup Service](https://www.ebi.ac.uk/ols/beta/index)? Both are much faster than BioPortal when it comes to searching for ontologies that already contain desired terms.

Kind regards,
Gareth
