### ISSUE TITLE
3-methylguanine lacks SMILES and other chemical data

### ISSUE THREAD

**Issue by cviner** [ebi-chebi/ChEBI#3177]
[CHEBI:1604 - 3-methylguanine](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:1604) lacks any SMILES annotation and therefore also lacks an image of its structure.

It is also missing all the usual information on its chemical properties (e.g. formula, net charge, average mass, etc.).

**Comment by G-Owen** [comment]
Hi Coby,

The purine (and pyrimidine) nucleobases are a problem for ChEBI. They are depicted in the literature in numerous ways (pyrimidin-one vs hydroxy-pyrimidine, etc.)- each structure being a tautomer of all the others. Some users want one particular tautomeric structure in order to depict a particular transformation mechanism, while others want a different tautomer to depict the binding to a particular protein, etc. So we have separate entries for each tautomer (linked together in the ontology by "is_tautomer_of" relationships); all of the tautomers are grouped under a "generic" class name (eg 3-methylguanine). Unfortunately, this means that we cannot give a structure (or SMILES, or InChI) for the generic entry, as any structure would have to be correct for all of the child tautomers .
We can, however, specify the formula and mass for the 'generic' entries. I'm not sure why it was missing from the "generic" class name for 3-methylguanine (CHEBI:1604), but I have now added it.

Best regards,
Gareth

**Comment by cviner** [comment]
That makes sense. Thanks for the detailed explanation and for adding those missing items!
