### ISSUE TITLE
Compound with InChI but without formula

### ISSUE THREAD

**Issue by bitbarbie** [ebi-chebi/ChEBI#3188]
I found a set of compounds that are annotated **with InChI and InChIKey but lack a molecular formula** (based on the downloaded obo file of release 2016-07-01).

All IDs have an entry in the obo file including the [Related InChI] tag. So I compared all ids manually with their homepage entry and was able to separate the following three groups:

_(1) ID has NO hit in Chebi online._
... although the id occurs in the obo file.
Suggestion: Old compounds that have been deleted in the meantime but are still in the obo? But for what?

_(2)  Chebi online entry has no molecular properties at all_
... although the id is annotated with an InChI in the obo file.
Suggestion: Maybe these should be classes?

_(3) Chebi online entry has InChI but no formula_
(two of those IDs overlap with the no smiles issue earlier #3171 )

Please find the lists attached.
[1_obo_entry_but_no_homepage_entry.txt](https://github.com/ebi-chebi/ChEBI/files/384035/1_obo_entry_but_no_homepage_entry.txt)
[2_noformula_noinchi_online.txt](https://github.com/ebi-chebi/ChEBI/files/384034/2_noformula_noinchi_online.txt)
[3_noformula_withinchi_online.txt](https://github.com/ebi-chebi/ChEBI/files/384033/3_noformula_withinchi_online.txt)

**Comment by G-Owen** [comment]
Thank-you for drawing these to our attention.

Problem set (1) are 1-star (preliminary) entries - mostly loaded from Kegg or PDBe. 1-Star entries have minimal information and are not shown on the public site until they are checked and updated. In the 10+ years since they were originally loaded, nobody has ever asked for them to be included in ChEBI, so they have remained hidden in the database as a starting point for a 3-star (fully checked) entry if they are ever requested. Originally, the 1-star entries did not have any associated structures and were not classified within the ontology. In the last year, most have now had (unchecked) structures added, and have been automatically classified within the structure ontology (also unchecked), so we should probably upgrade them to 2-star status to make them visible on the public website. We should be able to do this programmatically.

Problem set (2) appear to be class names which have partial structures. The structures are rather inadequate, so do not have 'checked' status, but have resulted in an InChI being generated and displayed. As there aren't very many of these, we will correct them manually.

Problem set (3) may have had some problem when the structure for an entry was being saved, resulting in a formula or smiles not being generated (I can see why the valencies/structure depicted for iron(III) dicitrate might cause problems!). Again, we will check these out and update them appropriately.

Kind regards,
Gareth
