### ISSUE TITLE
parabens

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3214]
current:

```
     is_a CHEBI:85122 ! paraben *** 
          is_a CHEBI:31575 ! Ethyl parahydroxybenzoate
          is_a CHEBI:31835 ! methylparaben
          is_a CHEBI:32063 ! propylparaben
```

For:

```
[Term]
id: CHEBI:31575
name: Ethyl parahydroxybenzoate
namespace: chebi_ontology
synonym: "C9H10O3" RELATED FORMULA [KEGG_COMPOUND]
synonym: "Ethyl parahydroxybenzoate" EXACT [KEGG_DRUG]
synonym: "Ethylparaben" RELATED [KEGG_DRUG]
xref: KEGG_DRUG:120-47-8
xref: KEGG_DRUG:D01647
is_a: CHEBI:85122  ! paraben
```

Add "ethyl paraben" as a syn (note: this only differs from an existing one by a space and capitalization - is there documented CHEBI policy on this)

Also add syns:

 * ethyl-p-hydroxybenzoate
 * ethyl-p-hydroxybenzoic acid

For: CHEBI:32063 ! propylparaben

Consider adding a synonym: n-propyl paraben

although this barely differs from the existing:

```
synonym: "N-Propylparaben" RELATED [HMDB]
```

**Comment by G-Owen** [comment]
Hi Chris,
I think these are now sorted. 
I have merged two preliminary ethylparaben entries and upgraded the merged entry (CHEBI:31575) to checked status.
The parabens are unusual nomenclature-wise in not having the space between the two words that make up the name of the ester (ethylparaben instead of ethyl paraben) - perhaps they started off as trade names - but both with- and without-space versions are found in the literature, so both versions are now in ChEBI.  
[For most esters, the space is very important - missing it out results in a totally different entity. E.g. phenyl acetate (with the space) is the phenyl ester of acetic acid, CH3C(=O)OPh, while phenylacetate (without the space) is the anion of phenylacetic acid, PhCH2C(=O)O- ]

We don't normally have 'different case' versions of the same name (although I'm sure there are a lot of cases in the database!).  The synonym you cite N-Propyl paraben is simply wrong (and doesn't appear on the public website) - it suggests that the propyl group is attached to a nitrogen (which the parabens do not contain). We will have to investigate why the unchecked synonyms are getting in to the ontology file, when they are excluded from appearing on the public site.
