### ISSUE TITLE
Add synonym: temefos

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3232]
* [CHEBI:38954](http://purl.obolibrary.org/obo/CHEBI_38954) - temephos

__ADD SYNONYM:__ temefos _to be consistent with:_ https://www.wikidata.org/wiki/Q21175337

(trivial but not all programs can do the f-ph substitution)

parent ticket: https://github.com/cmungall/environmental-conditions/issues/5

**Comment by cmungall** [comment]
Another trivial synonym. Is it your policy to add these? We can imagine a large cross-product where we have compositional terms...

 * [CHEBI:30334](http://purl.obolibrary.org/obo/CHEBI_30334) - phosphorus trichloride __ADD SYNONYM:__ phosphorous trichloride _from:_ https://www.wikidata.org/wiki/Q21175058

**Comment by G-Owen** [comment]
Both now done. Phosphor**o**us used to be used to denote the lower oxidation state of phosphorus (in a similar way to cuprous, ferrous, etc.), but has been largely abandoned in favour of names that are less prone to ambiguity ('phosphorus trichloride' etc.). However, the use of phosphor**ic** for the higher oxidation state (in a similar way to cupric, ferric, etc.) remains common, (especially phosphoric acid and its compounds), probably because it cannot be misinterpreted as a possible spelling mistake!
