### ISSUE TITLE
CHEBI:15642, the name is wrong, and KEGG x-ref invalid

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3287]
Hi,

This compound, CHEBI:15642, (6R)-6-(L-erythro-1,2-dihydroxypropyl)-5,6,7,8-tetrahydro-4a-hydroxypterin, is in fact D-erythro. KEGG has deleted its original structure C06486. Instead the have created C15522 that is wrongly cited in CHEBI:15374.

I have just submitted the correct structure, CHEBI:136571 and have add a cross reference to KEGG C15522

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,
As CHEBI:15642 seemed to have the right names but the wrong structure, I have merged it with your submission - the primary ID is CHEBI:15642.
Is there any evidence for the stereochemistry for the stereobond (shown in Kegg C15522) to the hydroxy group at the ring junction? I am slightly puzzled by the terminology "4alpha-hydroxy..... - the position would normally be termed 4a rather than 4alpha  -  with terms such as 4alpha, 3beta, etc., the greek letter would normally refer to the stereochemistry rather than position (as with steroids) - so I wonder whether it should be "4a-hydroxy..." rather than "4alpha-hydroxy..." ?

Cheers,
Gareth

**Comment by kaxelsen** [comment]
Hi Gareth,

I took the name from MetaCyc without considering it much. I asked Ron if they had a special reason for it, and as they have not, please change back to 4a
Cheers,
Kristian

**Comment by G-Owen** [comment]
Thanks, Kristian.

I have added a MetaCyc link (CPD-5881) to CHEBI:15642 and to the 'unspecified stereochemistry' version, CHEBI:15374 - structure-wise, it isn't a perfect match for either ChEBI entry, but one or more of the synonyms from both ChEBI entries matches with the MetaCyc entry.

Cheers,
Gareth
