### ISSUE TITLE
Broken large images

### ISSUE THREAD

**Issue by rafael-alcantara** [ebi-chebi/ChEBI#3309]
When I hover the structure image for ginkgolides (ex. http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:80750) I see the square for the big image and a broken icon, but not the big image.
This does not happen with water.
Thanks, old friends.

**Comment by G-Owen** [comment]
Hi Rafa,
I think this is due to the illegal use of stereobonds in the structure. The entire entry including the structure was imported from Kegg, and had not been updated in any way since. It included some stereocentres where a wedged bond was opposite to a dashed bond, which is not allowed - if you want to put two stereobonds to a stereocentre, the rule is that adjacent bonds are of opposite type (if one bond is wedged, the bond adjacent to it is dashed) or that opposite bonds are of the same type (if one bond is wedged, the opposite (i.e. non-adjacent) bond is also a wedge.
I updated the structure for CHEBI:80750 and it seems to have fixed the problem. I will look at the other ginkgolides when I get back to the office.

Cheers,
Gareth
