### ISSUE TITLE
CHEBI:80351 is identical to CHEBI:46734

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3358]
Hi,

Both these entries are named: (1E,4S,5E,7R)-germacra-1(10),5-dien-11-ol.
The InChI's are not identical, I don't know why (the position of the OH group?).

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,
I have merged the two entries - the parent ID is CHEBI:46734 (the original ChEBI entry).

The problem was with the structure on CHEBI:80351, which came from Kegg C16143. They used a "two 6-membered rings fused together" approach to draw the 10-membered ring skeleton, whereas we (actually Marcus!) used a "5-membered ring and a 7-membered ring fused together" approach. Using the Kegg method, the methyl group attached to the double bond ends up clashing with the other side of the ring if the double bond has E geometry. 
To avoid the clash, Kegg have drawn the methyl group outside the 10-membered ring, which means that the double bond has Z configuration, rather than the desired E configuration. That's why the InChIs were different!

I have deleted the Kegg structure from the merged ChEBI entry to avoid future confusion!

Cheers,
Gareth
