### ISSUE TITLE
classification of vitamin metabolic process

### ISSUE THREAD

**Issue by ValWood** [ebi-chebi/ChEBI#3362]
Hello,

I was wondering why vitamin metabolic process is not classified as a small molecule metabolic process in GO, but co-factor metabolic process is.

https://github.com/geneontology/go-ontology/issues/14047#issuecomment-322485261

It appears this may likely be due to the  non-classification of vitamin as a biochemical_role
(see GO tracker ticket for discussion).
Could you have a look if some  additional classification is required?

Thanks

Val

**Comment by G-Owen** [comment]
Hi Val,

I have initially reclassified: 
vitamin (CHEBI:33229) as _is_a_  micronutrient (CHEBI:27027)
                                              _is_a_  nutrient (CHEBI:33284)
                                                   _is_a_ food component (CHEBI:78295)
                                                        _is_a_  physiological role (CHEBI:52211)
[instead of vitamin is_a food component, which is_a physiological role].

Interestingly, the only child terms for physiological role (CHEBI:52211) are currently 'food' and 'food component'. In contrast, there are >50 child terms for biochemical role (CHEBI:52206). 
I'm no expert, but I am wondering whether 'physiological role and 'biochemical role' are more or less equivalent terms and so could be merged?  -  Please let me know your thoughts.

Kind regards,
Gareth

**Comment by ValWood** [comment]
I'm not sure. I think they could be slightly different.  I imagine that a food component could  have a physiological role, but not  a biochemical role. Even if this is only because it does not have a biochemical role until it is ingested. But I am not so familiar with CHEBI, so I am not sure how it is organised.

I think the relationship we are looking for is 
vitamin is_a 'biochemical role' 

 @deustp01 @ukemi is that correct?

**Comment by ValWood** [comment]
Hi Gareth. I now realise that this will not align  vitamin and co-factor as  "small molecule metabolism" in GO because  "citamins" and already classified as "small moelcule metabolic processes", it is cofactors which are not.

This must be because  vitamin metabolism has a parent  that cofactor metabolism does not. I will take a look.

**Comment by ValWood** [comment]
I now see our GO issue will not be fixed by this (because I got the problem the wrong way around) , apologies.
