### ISSUE TITLE
classes under both 'chemical entity' and 'biological role' unsatisfiable when used with GO

### ISSUE THREAD

**Issue by balhoff** [ebi-chebi/ChEBI#3390]
There are a few classes that are under both 'chemical entity' and 'biological role'. If you import both ChEBI and GO-plus into the same reasoner session, these classes will become unsatisfiable:

- [ ] C3 exoenzyme
- [ ] MMP9 Inhibitor I
- [ ] trans-Ned 19
- [ ] CAY10397
- [ ] IP3/BM

This comes from the GO-plus import file http://purl.obolibrary.org/obo/go/extensions/go-bridge.owl which equates [ChEBI role](http://purl.obolibrary.org/obo/CHEBI_50906) to [BFO role](http://purl.obolibrary.org/obo/BFO_0000023).

Should some subclass relationships be converted to ['has role'](http://purl.obolibrary.org/obo/RO_0000087) restrictions? I realize this issue stems from axioms outside of ChEBI being used with ChEBI, but it would be good for these to be compatible.

**Comment by G-Owen** [comment]
Hi Jim,

The five entries that you list are some submissions to ChEBI that we have not yet managed to check. By default, submissions are assigned as **is_a** organic molecular entity in the ontology, so connecting them to the chemical structure ontology. Unfortunately, they were submitted using is_a relationships linking them to the role ontology, instead of has_role relationships [e.g. IP3/BM (CHEBI:138527) **is_a** IP3 receptor antagonist (CHEBI:131186) instead of IP3/BM (CHEBI:138527) **has_role** IP3 receptor antagonist (CHEBI:131186)]. 
I have now changed the problematic is_a relationships in these submissions to has_role relationships. This should fix the problem for now (at least until the next problematic submission comes in!)

Best regards,
Gareth

**Comment by balhoff** [comment]
Thanks!
