### ISSUE TITLE
CHEBI:61313 - missing formula formula

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3416]
Dear Chebi curators,

Please would you update formula of CHEBI:61313 according to its 2D structure.
CHEBI:61313 is needed for Rhea.

Cheers, Anne

**Comment by G-Owen** [comment]
Hi Anne,

Sorry, but we can't do this. 
CHEBI:61313 (C21 steroid) is a 'generic' entry, with definition "A steroid that has a structure based on a 21-carbon (pregnane) skeleton." So the term includes not just pregnane but related compounds that may contain double bonds and/or epoxy, hydroxy, methoxy, oxo, etc. substituents. Although the skeleton itself has C21H36, most of the related compounds don't. So we cannot say that such compounds always have the formula C21H36, which is why the formula (which was was calculated from the structure) was deleted.

Best regards,
Gareth

**Comment by amorgat** [comment]
Dear Gareth,

I understand your concern.
However I need to create the reaction
A C(21)-steroid + [reduced NADPH--hemoprotein reductase] + O(2) = a 17-alpha-hydroxy-C(21)-steroid + [oxidized NADPH--hemoprotein reductase] + H(2)O.

I used CHEBI:61313 for "C(21)-steroid" and CHEBI:138141 for "17-alpha-hydroxy-C(21)-steroid"

To be consistent you should remove the formula of CHEBI:138141 too...
However, I find quite confusing to have an entry with a defined 2D structure but not formula.
Do you think we could add some R-groups? In the 2D structures and in the formula? BTW I could balance my reaction, and you show that these compounds are generic ones.

What do you think? If you have other proposal, do not hesitate ;-)
Cheers, Anne

**Comment by G-Owen** [comment]
Hi Anne,
I have made the formula and masses visible and added an explanation to the definition field for 61313 and 138141 (hopefully the ontologists using ChEBI won't protest too much!). See what you think.

Cheers,
Gareth

**Comment by amalik01** [comment]
I am going to close this issue as it has been open for some time now.
