### ISSUE TITLE
CHEBI:78352, is the structure correct

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#3422]
Dear Steve and Gareth,

I have a question regarding the stereo-configuration of this compound. A new article (pmid:28463490) has studied the compound in more detail. Gerry Moss has interpreted the structure as being:
cyclooctat-9-en-7-ol = (1R,3aR,4S,7R,9aR,10aR)-1,4,9a-trimethyl-7-(propan-2-yl)-1,2,3,3a,4,5,7,8,9,9a,10,10a-dodecahydrodicyclopenta[a,d][8]annulen-4-ol in EC 4.2.3.146

He had BEFORE defined cyclooctat-9-en-7-ol as (1S,3aS,4R,7S,9aS,10aS)-1,4,9a-trimethyl-7-(propan-2-yl)-1,2,3,3a,4,5,7,8,9,9a,10,10a-dodecahydrodicyclopenta[a,d][8]annulen-4-ol

I had a brief look at the paper and the structure there seemed to me to correspond to the structure of CHEBI:78352, but the IUPAC name is different. 

So I hope you will take a look and find out what is correct.

Cheers,
Kristian

**Comment by G-Owen** [comment]
Hi Kristian,
Thanks for drawing the 2015 paper (Angew. Chem Int Ed., v54, 4353-4356, pmid:28463490) to our attention.  Previous papers were depicting the enantiomer for both cyclooctat-9-en-7-ol and (CHEBI:78352) and for cyclooctatin (CHEBI:78370) . 
I agree with Gerry Moss regarding the stereochemistry.
I have now updated both ChEBI entries so that they fit with the 2015 paper. 

Cheers,
Gareth
