### ISSUE TITLE
two outdated HMDB links

### ISSUE THREAD

**Issue by egonw** [ebi-chebi/ChEBI#3495]
Two HMDB identifiers sources from HMDB are for a different ChEBI identifier for which they are given here, and HMDB no longer has the link. That is HMDB IDs are incorrect (outdated) for:

* https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:31690
* https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:49016

**Comment by amalik01** [comment]
Hi Egon, 

The links to HMDB seem to be working fine now.
We link ChEBI entries to HMDB based on both structures and synonyms, so that ChEBI entries for a parent compound and any corresponding ions/salts will all be matched onto the same HMDB entry. The structure however does not have to be exactly the same. For example a neutral compound in ChEBI and or it's conjugate acid/base and salts will be linked to the same parent structure in HMDB.
I hope this helps. If you require further clarification, please feel free to get in touch.

Cheers,
Adnan

**Comment by egonw** [comment]
OK, yes, clear. I thought I remembered ChEBI to have more precise links, and noting that HMDB did not have this link back to the salt... I guess I have to get use to the HMDB-ChEBI references to be more chemically accurate in HMDB than in ChEBI ;)

Thanks for the quick reply!

(More seriously, you could consider annotating the links between ChEBI and other databases ontologically, like the "scientific lenses" in Open PHACTS did, or the ontological links between entries in ChEBI itself...)
