### ISSUE TITLE
CHEBI:46979  please add more info

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3504]
US suppliers and Pub Chem seem to draw this in the opposite orientation so please check this info carefully to make sure the molecule is identical.  Partial submission ID 13431 can be used to verify that  PubChem CID:10427441 is equivalent to CHEBI:46979
Submission 13431  InChI=1S/C20H39NO3/c1-3-4-5-6-7-8-9-10-11-12-13-14-15-16-20(24)19(17-22)21-18(2)23/h15-16,19-20,22,24H,3-14,17H2,1-2H3,(H,21,23)/b16-15+/t19-,20+/m1/s1

InChI Key: BLTCBVOJNNKFKC-HEQKZDDYSA-N
 
If they are identical then it would be helpful to have both InChI keys available for searching ChEBI

 
New Synonyms
(2S,3R,4E)-2-(Acetylamino)-4-octadecene-1,3-diol
 N-acetoyl-D-erythro-sphingosine
N-Acetyl-D-sphingosine
 (2S,3R,4E)-2-(Acetylamino)-4-octadecene-1,3-diol
N-((2R,3S,E)-1,3-dihydroxyoctadec-4-en-2-yl)acetamide

**Comment by cerivs** [comment]
CAS numbers seem to be the same

**Comment by amalik01** [comment]
Hi,
Thank you for your recent message.
The compound structure in ChEBI (46979) and PubChem (CID: 10427441) are different stereoisomers. Unfortunately, PubChem have given the incorrect name to the structure which they have displayed.

The structure in ChEBI has the stereochemistry: 2S, 3R, 4E and the structure in PubChem (CID: 10427441) has the stereochemistry: 2R, 3S, 4E. Since the sterochemistry differs between the two structures, you have slightly different InChi keys for both structures.

The CAS number for the ChEBI structure is 3102-57-6
The CAS number for the PubChem structure is 150338-90-2

However, i was able to find the same structure as CHEBI: 46979 in PubChem which is  N-(Acetyl)-sphing-4-enine (PubChem CID: 5497136).

We have added the appropriate additional synonyms to the ChEBI entry (but not the synonyms which describe the wrong stereoisomer).

I hope this helps. If you require further clarification, please do not hesitate to contact us.

Best Regards,
Adnan
