### ISSUE TITLE
CHEBI:143075, please add synonym and is-a relationship

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3573]
Hi Adnan,

For CHEBI:143075, please
- add synonym 
<locant>gamma</locant>-aminobutanoyl-<stereo>L</stereo>-histidine
<locant>gamma</locant>-aminobutanoyl-<stereo>L</stereo>-His
--> it seems that XML tags are removed by GitHub... :-( 
- add is-a relationship to CHEBI:46761 (dipeptide)

BTW, note that CHEBI:46761 still has a KEGG formula status CHECKED, whereas the chebi formula and the 2D structure are status DELETED

Warm regards,
Anne

**Comment by amalik01** [comment]
Hi Anne,

Apologies for the late response.
I have added your synonyms to this entry. Since we had the dipeptide zwitterion term in ChEBI (CHEBI:90799). I have used this more accurate term instead of 2 separate terms (dipeptide + zwitterion). 

The reason why the dipeptide structure (CHEBI:46761) was marked as deleted was that the generic structure does not apply in all cases, especially when you are dealing with proline dipeptides or non-proteinogenic dipeptides which do not conform to this generic structure. Hence, i have now marked the KEGG formula as deleted.

I have kept the structure of the dipeptide zwitterion (CHEBI:90799) intact since you could be using this as you are the one who created this entry in ChEBI. I have added a comment to this entry to inform ChEBI users that the generic structure does not apply in all cases.

Adnan

**Comment by amorgat** [comment]
Thanks Adnan!
