### ISSUE TITLE
CHEBI:66924 is classified as an alpha amino acid anion

### ISSUE THREAD

**Issue by ukemi** [ebi-chebi/ChEBI#3581]
Should this be moved to be a subclass of CHEBI:37022, amino acid anion?

https://github.com/geneontology/go-ontology/issues/17056

**Comment by deustp01** [comment]
But creatine (ChEBI:16919) is not - an amino acid, but not an alpha amino acid.

**Comment by amalik01** [comment]
To be precise, creatine should be called an amino acid derivative rather than an amino acid.
I have now corrected the ontology relationships in ChEBI as follows:

creatine (CHEBI:16919) is a glycine derivative.
creatinate (CHEBI:66924) is a monocarboxylic acid anion
creatine zwitterion (CHEBI:57947) is a zwitterion
