### ISSUE TITLE
Charge should not be asserted for generic anions

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#3605]
http://purl.obolibrary.org/obo/CHEBI_29067 carboxylic acid anion

Has "Net Charge" of -1

However, this is a superclass of

http://purl.obolibrary.org/obo/CHEBI_35753 tricarboxylic acid anion

Which has a net charge of -3.

This seems odd. I don't think charge should be asserted for generic ions/anions/cations.

Or if it is asserted, it should be either just a sign (e.g. '-') or a different property (e.g. charge_direction) or a range (e.g. -1 to -4).

Ideally charge would not be modeled as an annotation property, but as an actual logical axiom, e.g. `citrate(4-) SubClassOf has-quality some '4- charge', with `4- charge` being itself axiomatized. This would allow us to explicitly state assumptions (e.g. N charge DisjointWith N+1 charge) and allow this to be checked by the reasoner

**Comment by cmungall** [comment]
Also, why is there no charge stated for classes like 'tricarboxylic acid dianion'?

https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_36300

**Comment by amalik01** [comment]
Hi Chris,

We are aware of this problem. We try not to add charges to general classes but sometimes when a structure is present, the program automatically assigns a charge based on the structure. I have deleted the -1 charge from CHEBI:29067

At the moment, we are unable to put a range or just a negative (-) symbol without an integer in the charge section. This issue can only be resolved when a new ChEBI schema is put in place which is unlikely to happen anytime soon due to resource constraints.

**Comment by amalik01** [comment]
The charge state of CHEBI:29067 had to be reverted since it is being used in several Rhea reactions.

**Comment by amorgat** [comment]
Thanks @amalik01 for the change.
@cmungall, we use some abstract ChEBIs (compound with R group and/or dummy atom) in Rhea.
For these compounds we need a formula and a charge to ensure the reactions are balanced (the Rgroup is supposed to be the same on each side of the reaction).
For instance, we have 44 reactions involving CHEBI:29067
https://www.rhea-db.org/searchresults?q=CHEBI%3A29067
We are aware that having a net charge for an abstract compound is quite weird, but we haven't found (yet) another solution.

**Comment by cmungall** [comment]
Hmm, and it would be incorrect to use the mono form: CHEBI:35757?

Even if this can't be fixed in the underlying CHEBI database, perhaps there is a way to do a post-database transformation in the OWL?

For my experimental OWL patternizer, I do the following:

 * create 'quality' classes for -1 charge, -2 charge, etc, and a grouping class 'negative charge'
 * Transform the charge property in CHEBI to an OWL axiom 'has-charge some X', *unless* it conflicts with a subclass assignment, in which case it can be rolled up a level.

Might it make sense to have this be part of the official CHEBI release?

**Comment by jannahastings** [comment]
@cmungall, in the case of CHEBI:29067, it is true that the class as a whole should just have *some* negative charge, but the particular structural representation (as a generic structure with the R group) definitely has just one negative charge (-1), thus, there is a sense in which the current annotation is not really incorrect, as the charge annotations are generated from the associated chemical structure representations. 

Of course, it would be better to say that *the particular associated structural representation of 'carboxylic acid anion'* has-charge -1, rather than the class as a whole. It would only be the structures that were generic for which this problem would apply, i.e. the structures containing 'R' groups or '*' query atoms. For these cases, it would be incorrect to assert 'has-charge some X' at the class level since you just don't know what else might be attached to subclasses. The presence of a generic R group or query atom could easily be determined with a cheminformatics check, which would allow those particular "has-charge" annotations to be treated differently to the other "has-charge" annotations. For the classes with fully specified structures (no 'R' groups etc.), the charge associated with the structural representation would also be the charge associated with the class.
