### ISSUE TITLE
Please update CHEBI:19591 & CHEBI:141205

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3609]
Hi Adnan,
I need to create a reaction with CHEBI:19591 and CHEBI:144070.
Please could you update the 2D structure of CHEBI:19591 to have the undefined configuration of the double bond defined as in CHEBI:144070.

BTW, I added the relationship
(E)-hex-2-en-1-ol (CHEBI:141205) is a hex-2-en-1-ol (CHEBI:144070)
The current is-a relationships of CHEBI:141205 are now incorrect.

Thanks for your support
All the best, Anne

**Comment by amalik01** [comment]
Hi Anne,

I have updated the structure of (CHEBI:144070) so that it is consistent with (CHEBI:19591).

We generally tend to avoid crossed double bonds in structures due to IUPAC guidelines for representing chemical structures (see section ST-4.4, http://publications.iupac.org/pac/2006/pdf/7810x1897.pdf). A wavy bond is generally preferred. A crossed double bond has sometimes been used to indicate unspecified double bond configuration or a mixture of configurations. 

Adnan

**Comment by amorgat** [comment]
Hi Adnan,
Thanks for the link, I didn't know that...
If you could send me an example with the right way, I can update my submission. In fact, I just wanted to be consistent!
@++
