### ISSUE TITLE
CHEBI:5556 invalid xrefs

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3642]
Hi

it looks the xref HMDB0014371 in not valid for CHEBI:5556.
HMDB0014371 is named "Guanadrel Sulfate" but is in fact "Guanadrel". HMDB0014371 does not contain any S atom.

**Comment by amalik01** [comment]
Thanks for letting us know. I have removed the link to avoid confusion.

ChEBI was linked to this HMDB entry because the common name for this entry is Guanadrel Sulfate. However, HMDB have diplayed the structure of guanadrel instead of Guanadrel Sulfate so the mistake is actually coming from HMDB. The structure shown does not match the name displayed in HMDB.
