### ISSUE TITLE
allose (CHEBI:37690) is both compound and class

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3659]
Please fix.

**Comment by amalik01** [comment]
This issue is difficult to fix. When the biological community mention allose, do they mean L-allose, D-allose or unspecified, or are they referring to the open-chain form or to the pyranose form. Since we do not know what the exact structure is, we create a class for it. The structure shown in wikipedia is not definitive.

We have the same issue with amino acids. When someone mentions alanine, are they referring to the naturally occurring L-alanine or do they mean D-alanine. If they do not know what it is, then we have to create a class called alanine. We then say L-alanine is an example of an alanine and D-alanine is a example of an alanine.
