### ISSUE TITLE
Add entry for erythromycin,[n-methyl-14c]

### ISSUE THREAD

**Issue by matthiaskoenig** [ebi-chebi/ChEBI#3680]
Currently there is no entry in CHEBI for Erythromycin,[n-methyl-14c]. This substance is applied in the erythromycin breath test and is a modification of erythromycin A (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:42355)

> The erythromycin breath test (ERMBT) is a method used to measure metabolism (oxidation and elimination from the system) by a part of the cytochrome P450 system. Erythromycin is tagged with carbon-14 and given as an intravenous injection; after 20 minutes the subject blows up a balloon and the carbon dioxide exhaled that is tagged with carbon-14 shows the activity of the CYP3A4 isoenzyme on the erythromycin.

https://en.wikipedia.org/wiki/Erythromycin_breath_test

The substance information is available from:
INCHIkey: ULGZDMOVFRHVEP-WCOQTRSGSA-N
https://pubchem.ncbi.nlm.nih.gov/compound/102601292
https://www.alfa-chemistry.com/cas_82343-12-2.htm

See references here
https://www.ncbi.nlm.nih.gov/pubmed/?term=%22erythromycin+breath+test%22%5Btitle%5D

Best Matthias

**Comment by amalik01** [comment]
Hi,
An entry has now been created (CHEBI:145339) and should become visible on the ChEBI website by tomorrow. By reading the literature, it seems that only one of the methyl groups of erythromycin has a 14C label instead of both methyl groups hence the structure which you are referring to is incorrect. The correct InChi is ULGZDMOVFRHVEP-RFAHSBMDSA-N . I hope this helps.
