### ISSUE TITLE
Issue submitting ontology for CHEBI:143797

### ISSUE THREAD

**Issue by aimol** [ebi-chebi/ChEBI#3690]
Dear ChEBI curators and developers,
I have CHEBI:143797 still in my submission tool and tried to add a child (CHEBI:143798), but the tool wont allow claiming: the compound being disconnected from the main ontology and asking to alter my modification. Can you please have a look? I do not see how adding children can alter the main ontology. Looking fwd to hearing from you soon as I need to add more children to this entity.
Best,
Lucila

**Comment by amalik01** [comment]
Try now, i have just changed one of the ontology relationships.

**Comment by aimol** [comment]
Hi, I have no more access to those 2 compounds, but I tried adding to others in my list successfully. Now I wanted to delete one of the relations I just added CHEBI:143803 is_a CHEBI:143797 but the same error appears and it does not allow me to remove this relation. Can you please check?

**Comment by amalik01** [comment]
The only way you can delete the existing relationship is when you add a new IS_A relationship to CHEBI:143803 and then delete the existing one since it needs to be connected to the tree before deleting it. Do you know what you want to classify CHEBI:143803 as?

**Comment by aimol** [comment]
I added the relation to CHEBI:143803:
CHEBI:143803 is_a CHEBI:142797
as the CHEBI:143797 is no longer available in my submission tool. 
3 min later I tried to delete this relation and the tool wont allow it claiming it alters the main ontology

**Comment by amalik01** [comment]
Hi Lucila,
But CHEBI:143803 is not a CHEBI:142797 (they are totally different structures). Let me know what IS_A relationship you need to add to CHEBI:143803 and i will do it manually.

**Comment by aimol** [comment]
Strange that we cannot delete this relation. I currently do not have any is_a that we can add, would need to submit a new entry for this

**Comment by muthuvenkat** [comment]
@aimol, there was an ontology validation bug which got fixed recently. Along with that if there is more than one "IS_A" relationship, then the "Organic Molecular entity" is deleted automatically in the submission tool to save the curator's time to delete. Submitters add exact relationship and also leave the default relationship "Organic Molecular Entity", making the ontology more redundant. If you try to create the same relationship in the submission tool, it won't let you do it now; the entry throw an error because the validation is fixed. We recommend you to add the outgoing (parent relationship) first before the incoming (child relationship).

**Comment by aimol** [comment]
Thanks for the explanation Venkat.
