### ISSUE TITLE
CHEBI:140525 and CHEBI:140471 - add missing relationships

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#3749]
Hi Adnan,
Please would you add some missing relations
CHEBI:140525 is-a CHEBI:17815
CHEBI:140471 is-a CHEBI:64615
Thank you!
Anne

**Comment by amalik01** [comment]
The first relationship has been added. The second relationship (CHEBI:140471 is-a CHEBI:64615) is not correct since the stereo configuration of the chiral carbon of the triacylglycerol moiety is unknown. The correct relation is (CHEBI:140471 is-a CHEBI:17855). If you can provide evidence that it should have (R)-configuration, then i can add in this new relation and change the existing structure.
