### ISSUE TITLE
NTRs

### ISSUE THREAD

**Issue by celineaubert** [ebi-chebi/ChEBI#3765]
Could you please add the terms below with the relation 
> has role **some** fertilizer

- [ ] Ammonium phosphate nitrate https://pubchem.ncbi.nlm.nih.gov/compound/19890334

- [ ] Ammonium phosphate sulfate https://pubchem.ncbi.nlm.nih.gov/compound/22222880

- [ ] Ammonium polyphosphate https://en.wikipedia.org/wiki/Ammonium_polyphosphate

- [ ] Ammonium thiosulfate https://pubchem.ncbi.nlm.nih.gov/compound/6096946

- [ ] Dicyandiamide (syn: DCD, Cyanoguanidine) https://pubchem.ncbi.nlm.nih.gov/compound/10005

- [ ]3,4-Dimethylpyrazole phosphate (syn:DMPP) https://pubchem.ncbi.nlm.nih.gov/compound/11446863

- [ ] Potassium metaphosphate  https://pubchem.ncbi.nlm.nih.gov/compound/Potassium-metaphosphate

@marieALaporte

**Comment by celineaubert** [comment]
- [ ] Struvite
parent: phosphate mineral http://purl.obolibrary.org/obo/CHEBI_46723
Synonym: Magnesium ammonium phosphate
Definition: a crystal of magnesium ammonium phosphate (MAP) with equal molar concentrations of Mg, ammonium (NH4), and P combined with six water molecules.
https://www.sciencedirect.com/topics/earth-and-planetary-sciences/struvite
https://pubchem.ncbi.nlm.nih.gov/compound/15894839
> has role **some** fertilizer

**Comment by amalik01** [comment]
The following entries have now been created. Some of them will be visible right now and some will be visible on the ChEBI website by tomorrow:

ammonium nitrate phosphate (CHEBI:147420)
ammonium phosphate sulfate (CHEBI:147419)
ammonium polyphosphate (CHEBI:147408)
ammonium thiosulfate (CHEBI:147402)
dicyandiamide (CHEBI:147423)
potassium metaphosphate (CHEBI:148438)
struvite (CHEBI:149427)
3,4-Dimethylpyrazole phosphate (CHEBI:148435) - I don't think this is a fertilizer, it is a nitrification inhibitor which is added to fertilizers. If you can find evidence of it being a fertilizer in the literature, send it to me so that i can add the fertilizer role to this entry.

**Comment by celineaubert** [comment]
Thanks for adding those classes to ChEBI! 
You are right 3,4-Dimethylpyrazole phosphate is used as a nitrification inhibitor and not directly as a fertilizer.
