### ISSUE TITLE
CHEBI:15815 probably has to be split

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#3796]
The entry for CHEBI:15815 quinolin-4-ol (aka 4-hydroxyquinoline) contains hyperlinks to its tautomer, 4-quinolone (CAS 529-37-3): 

https://www.emolecules.com/cgi-bin/more?vid=7533073
https://www.molport.com/shop/molecule-link/MolPort-003-986-116
https://www.chemicalbook.com/ChemicalProductProperty_EN_CB4372459

I suggest to either split CHEBI:15815 or create a new ChEBI entry for 4-quinolone, IUPAC name: quinolin-4(1H)-one
https://en.wikipedia.org/wiki/4-Quinolone

4-quinolone is a functional parent for CHEBI:16569, 3-hydroxyquinolin-4(1H)-one and CHEBI:29216, 3-hydroxy-2-methylquinolin-4(1H)-one

Cf. quinolin-2(1H)-one (CHEBI:18289) is tautomer of quinolin-2-ol (CHEBI:16365)

**Comment by amalik01** [comment]
I have now created a separate entry for 4-quinolone (CHEBI:155900). The entry should become visible on the ChEBI website by tomorrow.

We link to several chemical supplier websites such as eMolecules and MolPort via UniChem. Since these websites are using standard InChi's which don't differentiate between the two tautomers, we automatically generate 2 sets of links to each tautomer (since both tautomers will have the same standard InChI key). The same problem occurs for alot of the tautomers in ChEBI. Most chemical suppliers do not use non-standard InChI's which are able to distinguish one tautomer from the other.
