### ISSUE TITLE
CHEBI:31175 wrong structure / question

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#3835]
In CHEBI:31175 - adefovir pivoxil the pivoxil groups have both an -O- too much, see
https://en.wikipedia.org/wiki/Pivaloyloxymethyl.

Possibly I asked that before, would it help if I submit these issues as ready fixes in a pull request? The submission tool only allows new submissions, not changes to existing ones. I'm asking because, purely from the numbers, I expect several dozen more issues in the next weeks, as I'm going through my Wikidata list of discrepancies (799 to go, maybe 10% of these are issues in ChEBI).

**Comment by amalik01** [comment]
Thanks for letting us know. This has now been corrected.

Unfortunately you wont be able to do a pull request since the data and source code is not available on GitHub. In order to change the data in existing submissions, you will need access to ChEBI's curator tool and and carry out the changes manually by going to each individual entry. But even then you will not be able to change any 3-star entry (an entry which has already been annotated by a curator) or someone else's submissions. 

Most of the inconsistencies are found in 2-star entries which have been loaded into ChEBI from an external source and haven't yet been checked by a ChEBI curator. Such entries have been in the database for years, and we are unable to check every single one of them and mark them to 3-stars due to limited resources. If you send a list of issues, i will try my best to go through the list and correct the inconsistencies in the database.
