### ISSUE TITLE
Deprecated xref for CHEBI:6078

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3934]
Hi
CHEBI:6078 (ivermectin) looks to have a deprecated xref:
- HMDB HMDB0014740 entry does not exist any more.

Also KEGG D00804 and CHEBI:6078 formulae do not match (R group is not at the same level). Could it be harmonized?

**Comment by amalik01** [comment]
The HMDB ref has been deleted.  In ChEBI, we generally do not show the structures of mixtures. Sometimes, for depiction purposes a general structure is shown such as the one found in CHEBI:6078. For mixtures it is difficult to show what the exact formula is since the formula is the combination of the 2 components hence both the ChEBI structure and Kegg structure are both valid.
