### ISSUE TITLE
Wrong xref for CHEBI:28547

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3937]
Hi

KEGG C05385 xref to CHEBI:28547 looks wrong:
- CHEBI:28547 has no stereo to link the phosphate group, but KEGG C05385 has.

CHEBI:16787 looks properly linked to KEGG C05385.

But CHEBI:16787 has an xref to KEGG C01195 which does not exist.

**Comment by amalik01** [comment]
We map to KEGG based on structures and names. KEGG is all over the place in terms of chemical nomenclature, especially compound names.

One of the names of KEGG C05385 is D-Glucuronate 1-phosphate. The word 'glucuronate'  in the name refers to the  'carboxylic acid anion' form of this sugar, however the structure shown by KEGG is that of the free acid and should be referred as 'glucuronic acid' but it isn't by KEGG. This is why multiple ChEBI entries are sometimes matched to the same KEGG entry. The issue is that KEGG does not differentiate between neutral compounds and their corresponding ions whereas ChEBI does.
