### ISSUE TITLE
Copper chelate

### ISSUE THREAD

**Issue by Nizal-Shammry** [ebi-chebi/ChEBI#3960]
Dear ChEBI curators,

I am looking for the compound: Copper chelate 
Ref: https://pubchem.ncbi.nlm.nih.gov/compound/Copper-chelate
Does it exist in ChEBI in different name? if not.  Could you please add it.

Regards

**Comment by amalik01** [comment]
We don't have this term in ChEBI since Copper chelate is a vague name. Any compound containing a ligand bonded to a central copper atom would be classified as a copper chelate. The structure shown in pubchem is just one example. The closest match we have in ChEBI is chelator (CHEBI:38161). If you want, i can create a new entry called copper chelator but this would not have a structure associated with the entry.

**Comment by Nizal-Shammry** [comment]
Thank you for your quick reply. Yes please add a new entry for copper chelate.

**Comment by Nizal-Shammry** [comment]
Does ''capsular polysaccharide'' compound also a vague name?

Ref: https://pubchem.ncbi.nlm.nih.gov/compound/Capsular-polysaccharides-K87

**Comment by amalik01** [comment]
capsular polysaccharides is a class of compounds so doesn't have a definitive structure. I have now created 2 ChEBI entries:

capcular polysaccharide (CHEBI:3379)
copper chelator (CHEBI:166831)

These entries should be searchable on the ChEBI website by tomorrow. Thanks
