### ISSUE TITLE
CHEBI:143903 has weird H+ out of the molecule

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#3968]
Hi

I wonder why CHEBI:143903 has an explicit Hydrogen out of the molecule.

Its base and tautomer don't have it.

**Comment by amalik01** [comment]
Since the structure contains two primary amino groups and both can potentially be protonated. We do not necessary know which one is actually protonated hence we add an additional H+ with the structure to show that one of the amino groups is protonated. This is an acceptable approach as suggested by IUPAC (see section GR-7.3 salts drawn in unspecified form, http://publications.iupac.org/pac/pdf/2008/pdf/8002x0277.pdf). I hope this helps.
