### ISSUE TITLE
Tow entities for Fenipropidin?

### ISSUE THREAD

**Issue by andschar** [ebi-chebi/ChEBI#3969]
I queried the CAS and received the two results [CHEBI:83291](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:83291) and [CHEBI:81917](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:81917). Aren't these the same entity? At least according to [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/91694).

**Comment by amalik01** [comment]
Hi,

Thanks. I have now removed the CAS number from CHEBI:83291 since this entry contains unspecified stereochemistry.

The issue is that most databases do not distinguish between unspecified stereo-chemical structures wheras ChEBI does. Most databases including PubChem will be showing the structure of fenpropidin as unspecified but this isn't correct since fenpropidin (CHEBI:81917) contains one stereocenter, therefore it is a racemic mixture comprising of equimolar amounts of both the (R)- and (S)-enantiomers. At the moment, we are unable to display two structures side-by-side for a given ChEBI entry hence we do not show the structure for the racemate, but in the ontology we mention that it has part the R-enantiomer and part S-enantiomer, so you can view the components of this racemate which are (CHEBI:83293 and CHEBI:83294). 




ChEBI:83291 is

**Comment by andschar** [comment]
Thanks for the clarification!
