### ISSUE TITLE
retinoid (CHEBI:26537) parent

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4020]
retinoids (CHEBI:26537) are defined as

"Oxygenated derivatives of 3,7-dimethyl-1-(2,6,6-trimethylcyclohex-1-enyl)nona-1,3,5,7-tetraene and derivatives thereof."

This compound, however, does not exist yet in (released version of) ChEBI. The hydrocarbon parent of retinoids is the "basic hydrocarbon" that JCBN refers to as "deoxyretinol" or "axerophthene" 
https://www.qmul.ac.uk/sbcs/iupac/misc/ret.html#p41

It corresponds to CAS 6895-29-0 and PDBeChem:AZE
ALL-TRANS AXEROPHTHENE or 2-[(1*E*,3*E*,5*E*,7*E*)-3,7-dimethylnona-1,3,5,7-tetraen-1-yl]-1,3,3-trimethylcyclohexene

So 
deoxyretinol **is a** diterpene (CHEBI:35190)
retinoid (CHEBI:26537) **has parent hydride** deoxyretinol

Links
https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/AZE
https://chem.nlm.nih.gov/chemidplus/rn/6895-29-0

**Comment by amalik01** [comment]
An entry has now been created for axerophthene (CHEBI:40918).

The issue with having deoxyretinol as the parent hydride of retinoid (CHEBI:26537) would be slightly misleading since there are children in this class which have double bonds in the cis-configuration and also 3rd/4th generation retinoids whose structures are completely different.
