### ISSUE TITLE
1-star entries cannot be resubmitted

### ISSUE THREAD

**Issue by rwst** [ebi-chebi/ChEBI#4025]
The problem with 1-star entries is that the resp. compounds are frozen, i.e. they cannot be created fresh from the community because the submission tool blocks progress because it would be a duplicate. This affects Reactome too because these are drug compounds I would have created if they weren't already existing 1-stars. Examples: ChEBI:40629, ChEBI:47575.

I cannot give a good suggestion, maybe don't block submission if the duplicate is 1-star?

**Comment by amalik01** [comment]
Hi,

We are aware of this issue. We currently have a backlog several thousand 1-star entries in ChEBI which require updating to 2-stars. Unless these entries are updated to 2-stars, you will not be able to add additional data to these entries. Our medium-term plan is to update these entries so that users can add additional data to such entries, but we are also limited in terms of resources at the moment. In the meantime, if there are urgent entries which require updating, send me the ChEBI ID's and i will update them manually.

**Comment by rwst** [comment]
Thanks for the info. In principle it suffices for Reactome to have a correct compound ID.

**Comment by amalik01** [comment]
I have now updated CHEBI:40629 and CHEBI:47575 hence both of these entries are now 3-star entries.
