### ISSUE TITLE
fluorescein (CHEBI:31624)

### ISSUE THREAD

**Issue by K-r-ll** [ebi-chebi/ChEBI#4088]
Please add PDBechem ref: FLU (and 3-D structure) to fluorescein (CHEBI:31624)

PDB references:

1flr
1n0s
1t66
1x9q
2nmv
4zs2
5dyo
5tsv
5tsx
6ayl

Literature references:

PMID: 7873555
PMID: 15836438
PMID: 19603796
PMID: 26744790 
PMID: 2104617
PMID: 13611166 
PMID: 3937554
PMID: 33661250
PMID: 29237120
PMID: 27303817 
PMID: 26675489
PMID: 21443768 
PMID: 17076510
PMID: 17097086
PMID: 16307475
PMID: 15352064
PMID: 9294871
PMID: 7696460
PMID: 8030782
PMID: 20725378
PMID: 8637844
PMID: 12945055
PMID: 15178254
PMID: 17097086
PMID: 26457839
PMID: 31620443 
PMID: 30772364 
PMID: 29065823 
PMID: 28781922 
PMID: 28490862
PMID: 27833927 
PMID: 24614144 
PMID: 24756415 
PMID: 24709799
PMID: 23363235 
PMID: 23737658
PMID: 8341496
PMID: 1854691 
PMID: 6192565
//

These two relationships are wrong:

calcium green 1(6−) (CHEBI:52958) **is a** fluorescein (CHEBI:31624)
eosin 5-isothiocyanate (CHEBI:60597) **is a** fluorescein (CHEBI:31624)

please replace with

calcium green 1(6−) (CHEBI:52958) **has functional parent ** fluorescein (CHEBI:31624)
eosin 5-isothiocyanate (CHEBI:60597) **has functional parent ** fluorescein (CHEBI:31624)

//

**Comment by amalik01** [comment]
The citations have been added and the ontology relationship have been corrected. 

We no longer provide links manually to PDB. All links created to PDB are done automatically via Unichem which maps via InChi keys. Since fluorescein can exist in multiple forms (lactone, acid, zwitterion etc). The structure shown in ChEBI is that of the lactone form hence the UniChem tool is unable to find the exact InChi key of this structure in the PDB so no links are provided. The structure of fluorescein shown in the PDB is that of the acid form and if you want, i can create a separate entry for the fluorescein acid form in order to form links to PDB. Let me know what you would like to do.

**Comment by K-r-ll** [comment]
Hello,

Yes indeed the best course of action is to leave the current entry as a lactone form (structure #1) and create the acid form (structures #2 and #3, which correspond to PDBechem:FLU), maybe giving them names like "fluorescein lactone" and "fluorescein acid" and make 

fluorescein lactone **has functional parent** fluorescein acid

Since "fluorescein acid" is no loger a benzofuran or a spiro compound it should be given a different place in ontology, e.g. 

fluorescein acid **is a** organic heterotetracyclic compound (CHEBI:38163)

**Comment by amalik01** [comment]
These 2 entries have now been separated:
fluorescein (lactone form) - CHEBI:31624
fluorescein (acid form) - CHEBI:172923
