### ISSUE TITLE
Reverse stereo for oligomycin A

### ISSUE THREAD

**Issue by smoretti** [ebi-chebi/ChEBI#4110]
Hi

CHEBI:28285 cross-references KEGG:C11311 (and vice-versa) but the stereochemistry of both molecules looks inverted: front and back stereos are inverted.

KEGG:C11311 looks more similar to CHEBI:95353 but is not linked to that one.

So what is the right oligomycin A structure?

**Comment by amalik01** [comment]
Hi, 

The structures of all the oligomycins in ChEBI were recently updated and are now in agreement with crystallographic evidence. The structures of oligomycin A in ChEBI is in agreement with the X-ray crystal structure of this compound and I have also now added a 3D structure of this compound to this entry. 
We map to other databases based on chemical names and InChi Keys and for this reason CHEBI:28285 has been mapped to KEGG C11311 entry. You will need to contact KEGG directly in order to update the structure in KEGG.

**Comment by amalik01** [comment]
The structure found in CHEBI:95353 was loaded into CHEBI from the LINCS database. It seems that this particular structure has been deprecated in LINCS so I have marked this ChEBI entry as deleted.
