### ISSUE TITLE
phorbol 13-acetate 12-myristate (CHEBI:37537)

### ISSUE THREAD

**Issue by slaulederkind** [ebi-chebi/ChEBI#4128]
phorbol 13-acetate 12-myristate (CHEBI:37537) in the ChEBI ontology is a child term of, among others, antineoplastic agent (CHEBI:35610).  The problem is that phorbol 13-acetate 12-myristate is a tumor promoter.  Check MESH:D013755, https://en.wikipedia.org/wiki/12-O-Tetradecanoylphorbol-13-acetate, and many references in PubMed.

**Comment by amalik01** [comment]
The issue is that in some cell lines, the compound behaves as tumour promotor whereas in others, the same compound has a strong antiproliferative effect (see PMID: 18541361 , PMID: 32640883).

**Comment by slaulederkind** [comment]
“antineoplastic” refers to tumor growth, not in vivo antiproliferative activity.

**Comment by amalik01** [comment]
Here is another paper (https://clincancerres.aacrjournals.org/content/12/11/3444.full-text.pdf) which shows that the compound is able to inhibit the growth of xenograft tumors in mice as a single agent. I would say that this is a strong indication that the compound behaves as an antineoplastic agent.

**Comment by amalik01** [comment]
In a different study (https://pubmed.ncbi.nlm.nih.gov/2866623/), the same compound behaves as a carcinogen. We usually extract the biological roles for the chemicals from the scientific literature. Since the role of this particular chemical is controversial, i have added both roles (antineoplastic agent, carcinogen) to the same ChEBI entry.

**Comment by slaulederkind** [comment]
Thank you, showing both roles will be better than showing only one.

**Comment by amalik01** [comment]
Great. I will close this ticket.
