### ISSUE TITLE
NTR: small molecule

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4140]
(apologies if this has been requested and rejected before, but I couldn't find in the tracker)

It would be great if CHEBI could have a class for "small molecule"

At the moment GO hardcodes which molecules are small molecules, and we end up making the assertion 6x in binding, metabolism, biosynthesis, transport, etc cc @pgaudet

https://github.com/geneontology/go-ontology/issues/14047

This comes up a number of other places a lot and I think the broader community would find it really useful if CHEBI had this grouping, e.g.

https://github.com/biolink/biolink-model/issues/881

**Comment by mikebada** [comment]
(reposted from Translator/biolink thread)

It's certainly a useful term, though some complicating factors to consider:

(1) Many (but not all) sources classify small molecules as organic compounds, though I'm guessing Translator folks would want the class to to be broader than that
(2) Many (but not all) sources classify small molecules as polyatomic compounds, though Translator folks have established that they want monoatomic entities (particularly ions, at least biologically relevant ones) included
(3) ChEBI defines `molecule` with its narrow chemical definition, i.e., of being electrically neutral, though I'm pretty sure Translator folks would want the class to be broader than that, in which case `CHEBI:small molecule` would not be subsumed by `CHEBI:molecule`

So, to encompass these broader dimensions (i.e., organic and inorganic, polyatomic and monoatomic, electrically neutral and ionic), perhaps request and use `small molecular entity`, as a subclass of the existing `CHEBI:molecular entity`?

**Comment by amalik01** [comment]
Adding a class called 'small molecule' to ChEBI is challenging and would create more issues than it solves and therefore not recommended. According to IUPAC, a molecule is electrically neutral hence the term 'small molecule' cannot include other entities such as ions. Furthermore, around 90% of the ChEBI database can be classified as 'is_a small molecule' and we don't have the curation resources to re-arrange the ChEBI hierarchy since this will require significant human intervention and time.
