### ISSUE TITLE
chebi:172945 9-cis-retinoyl-beta-D-glucuronide, maybe needs a review

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4192]
Hi ChEBI team,

I created some time ago this compound, and now I realize there are many various sources where this compound is reported but with a different formula, C26H36O8, instead of C26H38O7 such as currently in chebi:172945.

see for example

https://www.alfa-chemistry.com/cas_153321-67-6.htm

or

https://www.chemicalbook.com/ProductChemicalPropertiesCB51176103_EN.htm

or

https://www.carbosynth.com/carbosynth/website.nsf/(w-productdisplay)/ADBBC00D2D4D9DD0802573A0005C1F75

I  am wondering what is the reason for the formula to be different there? even using the mol file (153321-67-6.mol) available from 
https://www.chemicalbook.com/ProductChemicalPropertiesCB51176103_EN.htm
gives the same formula as the one I put in my chebi:172945 submission, C26H38O7, so why does a google search with '153321-67-6' reports C26H36O8 ?

Many thanks for your help in understanding such messy stuff!
Cheers,

Anne

**Comment by amalik01** [comment]
Hi Anne,

The structure is ChEBI was missing an oxo group so this has now been fixed. The correct formula is C26H3608.
Unfortunately alot of the suppliers have also got the structure wrong since their structure is missing an oxo group but their formula seems correct.

The word 'retinoyl' in the ChEBI name implies that an acyl group should be present in the structure.
