### ISSUE TITLE
Remove EM synonyms from Glu-Met

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4201]
http://purl.obolibrary.org/obo/CHEBI_73507

Synonyms | Sources
-- | --
E-M | ChEBI
EM | ChEBI
L-Glu-L-Met | ChEBI

are the top two synonyms correct? If so can we add provenance.

or perhaps they are errors, something to do with bad parsing of lab codes? They are certainly giving us false positives in NER

cc @hrshdhgd

**Comment by amalik01** [comment]
The synonyms are correct. For peptides (e.g. dipeptides, tripeptides, tetrapeptides) we tend to use the amino acid 1 letter codes to represent them in addition to the 3-letter codes (see table https://www.fao.org/3/y2775e/y2775e0e.htm).
1-letter codes are quite frequently used in journal articles to represent the peptides.

**Comment by cmungall** [comment]
ah I see you do this for individual NA bases and individual AAs too

ideally this would be a separate property like has-sequence but if that is too hard what about annotating the synonym with more info than just "ChEBI", e.g. "SEQUENCE"

**Comment by amalik01** [comment]
The source ChEBI just means the the synonym has been provided by the ChEBI team. If the source is ChemIDplus, it means that the synonym has been obtained from the ChemIDplus database.

Instead of type 'synonym', we could potentially label it as type 'sequence' but this is something we will need to think about when we redevelop ChEBI.
