### ISSUE TITLE
CHEBI:182953 and CHEBI:783 have same xref, error or to merge?

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4210]
Hello Chebi Team,

Wondering about CHEBI:182953 (not reviewed) (20S)-Cholesta-5-ene-3beta,17,20-triol, compared to CHEBI:783 (20R)-17α,20-dihydroxycholesterol?
Both have xref to Kegg C05499 17alpha,20alpha-Dihydroxycholesterol, which has a mol file corresponding to a name description such as '(20S)-Cholesta-5-ene-3beta,17,20-triol', right? 
Thank you in advance for advice
Cheers,

Anne

**Comment by ANiknejad** [comment]
By the way, xref LMST04030176  could be added to CHEBI:783 (20R)-17α,20-dihydroxycholesterol, right?

**Comment by amalik01** [comment]
I have added the lipid Maps link.
CHEBI:783 is the (20R)-stereoisomer whereas CHEBI:182953 is the (20S)-stereoisomer. I have removed the KEGG X-ref from 
CHEBI:182953 since i believe KEGG have got the structure wrong. They are showing the 20alpha position as 20S, but it should be 20R hence name does not match the structure shown.
