### ISSUE TITLE
wrong formulae for NAE and NASer (N-acyl amines)

### ISSUE THREAD

**Issue by ANiknejad** [ebi-chebi/ChEBI#4234]
Hello ChEBI team,

there are error in formula for N-acyl ethanolamine (see issue #4233) and for N-acyl serine

- CHEBI:134166 N-acylserine 16:0

correct formula should be C19H37NO4, as this is correct in CHEBI:165558 N-Palmitoyl serine, a 2-star entry that still needs review, and merge

As a consequence, wrong formula in 
CHEBI:134167 N-acylserine 16:1

- CHEBI:134168 N-acylserine 18:0

correct formula should be C21H41NO4, as this is correct in CHEBI:165572 N-Stearoyl serine, a 2-star entry that still needs review, and merge

As a consequence, wrong formula in 
CHEBI:134169 N-acylserine 18:1
CHEBI:134170 N-acylserine 18:2

- CHEBI:134171  N-acylserine 20:4  

correct formula should be C23H37NO4, as this is correct in CHEBI:143514 N-arachidonoyl-L-serine

As a consequence, wrong formula in 
CHEBI:134172 N-acylserine 20:6 should be C23H33NO4

**Comment by amalik01** [comment]
I have corrected the formula, mass and monoisotopic masses of these entries.
I haven't merged any of the entries as you suggested since they are separate entries. The correct way would be to fix the hierarchical structure of the ontology. For example N-Palmitoyl serine (CHEBI:165558) **is_a** N-acyl-L-serine 16:0 ( term currently missing in ChEBI) **is_a** N-acylserine 16:0 (CHEBI:134166) **is_a** N-acylserine (CHEBI:134123).
