### ISSUE TITLE
CHEBI:25805 - oxygen atom and CHEBI:29194 - monooxygen - same thing?

### ISSUE THREAD

**Issue by alanbridge** [ebi-chebi/ChEBI#4239]
Hi Adnan

hope you are doing well. 

I'm looking at atoms and monoatomic entities at the moment - I came across these two: 

```
CHEBI:25805 - oxygen atom
oxygen atom (CHEBI:25805) is a nonmetal atom (CHEBI:25585)
oxygen molecular entity (CHEBI:25806) has part oxygen atom (CHEBI:25805)
oxygen-15 atom (CHEBI:36932) is a oxygen atom (CHEBI:25805)
oxygen-16 atom (CHEBI:33818) is a oxygen atom (CHEBI:25805)
oxygen-17 atom (CHEBI:33819) is a oxygen atom (CHEBI:25805)
oxygen-18 atom (CHEBI:33815) is a oxygen atom (CHEBI:25805)
oxygen-19 atom (CHEBI:36933) is a oxygen atom (CHEBI:25805)
```

and 

```
CHEBI:29194 - monooxygen
monooxygen (CHEBI:29194) is a monoatomic oxygen (CHEBI:33264)
```

both have the same InChIKey: QVGXLLKOCUKJST-UHFFFAOYSA-N

Could they be merged?

that would then introduce this relationship: 

`oxygen atom (CHEBI:25805) is a monoatomic oxygen (CHEBI:33264)`

Would that be allowed? It might be a little hard to understand without more explicit definitions though.

All the best, Alan

**Comment by amalik01** [comment]
These entries cannot be merged as they are separate entries (I have already forwarded you Kirill's response by e-mail  which i will paste below). The InChi trust makes the following statement about radicals:
![image](https://user-images.githubusercontent.com/41328040/167149124-5d8db24e-1843-4770-a326-e19853412a90.png)

I think InChi is not able to distinguish between an oxygen atom and an oxygen atom with a radical and this is probably the reason why its giving the same InChi Key.

**Comment by amalik01** [comment]
Kirill's response:

I'll try my best to explain our thinking at the time.

The word "entity" is not used consistently throughout ChEBI.
The top term chemical entity (CHEBI:24431) is really an umbrella for four different ontologies. I wish it was called something else, e.g. "material system".

CHEBI:24431 chemical entity
  CHEBI:59999 chemical substance
  CHEBI:23367 molecular entity
  CHEBI:24433 group
  CHEBI:33250 atom

The only "real" entity is molecular entity (CHEBI:23367). Any molecular entity, at least in principle, should be able to "live its own life" (e.g. in vacuum).

On the contrary, group (CHEBI:24433), by definition, does not exist on its own but only as a part of a molecular entity. A group can contain one or more atoms. For example oxo group (CHEBI:46629) consists of one oxygen atom and a double bond attached.

Then there is atom (CHEBI:33250). An atom could exist as either standalone entity or as a part of a group or molecular entities. So when we read "oxygen atom" in literature, it can refer to two conceptually different things: either to a monoatomic entity (CHEBI:33238) that consists of one oxygen atom only -- then it will be better to call it monoatomic oxygen (CHEBI:33264) -- or to a part of either group or molecular entity, in which case it is better to say oxygen atom (CHEBI:25805).

Any oxygen molecular entity (CHEBI:25806) has part oxygen atom (CHEBI:25805) -- that is true statement.

But we cannot say that any oxygen molecular entity (CHEBI:25806) has part monoatomic oxygen (CHEBI:33264).

So oxygen atom (CHEBI:25805) is not classified as is_a monoatomic oxygen (CHEBI:33264) because some -- in fact most -- of the oxygen atoms are not standalone but parts of oxygen molecular entities (CHEBI:25806).

monooxygen (CHEBI:29194) is an uncharged type of monoatomic oxygen (CHEBI:33264); there are also several charged types of monooxygen that exist as (standalone) entities.

InChI only make sense for molecular entities. IMHO there should not be InChIs for "atoms" in ChEBI at all.
For example, for monooxygen (CHEBI:29194) InChI=1S/O; oxygen atom is just that "O" in InChI.

Note that we didn't do this kind of distinction (like in atom vs monoatomic entity) for subatomic particles: e.g. there are no separate entries for free electrons and bound electrons etc. although I can imagine situations when the annotators may want it.

The usefulness of the concept of "atom" could be seen if we try to write nuclear reactions such as

oxygen-15 atom (CHEBI:36932) → nitrogen-15 atom (CHEBI:36934) + positron (CHEBI:30225)

or

carbon-11 atom (CHEBI:36929) → boron-11 (CHEBI:52451) + positron (CHEBI:30225) + electron neutrino (CHEBI:30223)
[btw boron-11 (CHEBI:52451) should be properly called "boron-11 atom"]

Here we don't care whether, say, oxygen-15 atom is monoatomic oxygen or a part of molecular entity.
