### ISSUE TITLE
Request term for Branched-chain keto acids

### ISSUE THREAD

**Issue by DeniseSl22** [ebi-chebi/ChEBI#4240]
We would like to see an ontology term in ChEBI describing the branched-chain keto acids specifically (comparable to the branched-chain amino acids one, [CHEBI:22918](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:22918); we would like to use this term in WikiPathways and cannot find a more suitable one now. This new term could be a subclass of oxo carboxylic acid, [CHEBI:25754](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25754).

@mariavandemeent @egonw @mkutmon .

**Comment by amalik01** [comment]
@DeniseSl22 An entry has now been created (CHEBI:191197). If you know of any compounds which fall under this class, then please send me a list and i will add them to the database.

**Comment by DeniseSl22** [comment]
@amalik01 thank you for the quick response. Branched-chain keto acids (BCKAs; α-ketoisocaproate, α-keto-β-methylvalerate, and α-ketoisovalerate):

α-ketoisocaproate --> CHEBI:17865
α-keto-β-methylvalerate --> CHEBI:28654
α-ketoisovalerate -->  CHEBI:11851

**Comment by amalik01** [comment]
I have also created a separate entry for the conjugate base (branched-chain keto acid anion - CHEBI:191201). The data will get indexed overnight and this new entry will be searchable on the ChEBI website by tomorrow. All 3 of the above compounds have been added to this new class since they are ionized.
