### ISSUE TITLE
CHEBI:58753 IUPAC name

### ISSUE THREAD

**Issue by amorgat** [ebi-chebi/ChEBI#4243]
Hi Adnan,
I updated the UniProt name of CHEBI:58753 to ADP-β-D-ribose 1''-phosphate.
Please could you confirm you consider it as correct as I'm a little bit confused with its IUPAC name which mention alpha anomer: adenosine 5'-[3-(1-O-phosphonato-α-D-ribofuranos-5-O-yl) diphosphate] 
Thank you for your support
Cheers, Anne

**Comment by amalik01** [comment]
Hi @amorgat 

Again the UniProt name is incorrect since the sugar attached to ADP is an α-D-ribofuranose sugar so naming it as β-D-ribose is not correct. Please change the UniProt name to ADP-α-D-ribose 1''-phosphate.  The confusion is probably due to the two sugars in the structure. The sugar in ADP has β-D-configuration  (see ADP entry in ChEBI: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16761) so this will be ignored when naming the structure whereas the terminal sugar which has the phosphate group attached has α-D-configuration. When naming the structure, you basically ignore the stereochemistry of the ADP sugar since you know it has  β-D-configuration .

**Comment by amorgat** [comment]
Hi @amalik01, You're right. I have updated the UniProt name accordingly (as well as CHEBI:76596 UniProt name).
Thank you for your feed-back.
