### ISSUE TITLE
Ontology question

### ISSUE THREAD

**Issue by kaxelsen** [ebi-chebi/ChEBI#4266]
Hi Adnan,

I'm just now creating a number of flavonol oxoanions, and I see that existing ones either have the relationship 
is a flavonoid oxoanion (CHEBI:60038), others
is a  flavonol oxoanion (CHEBI:58588).

I'm in doubt when to use which as I'm not quite sure what the difference between them are.

Cheers,
Kristian

**Comment by amalik01** [comment]
Flavonoids are natural products derived from 2-phenylchromen-4-one (flavone - CHEBI:42491). Flavonols are a subclass of flavonoids that contains a hydroxy group at position 3 (see https://en.wikipedia.org/wiki/Flavonols).

I have now fixed the ontology so that a 'flavonol oxoanion is_a flavonoid oxoanion'.
