### ISSUE TITLE
Arbinitol needs a enantiomeric unspecific smiles and formula.

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4340]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:22605

**Comment by sorenwacker** [comment]
And maybe it should be renamed to Arabitol? I am a bit confused the the naming. Some sources refer to Arabitol and Arabinitol as the same substance, others say they are enantiomers. If so, then Arbitol is missing in the ChEBI database.

**Comment by K-r-ll** [comment]
No, it should **not** be renamed. The IUPAC approved name is "arabinitol".

See: IUPAC-IUBMB Joint Commission on Biochemical Nomenclature (JCBN), [Nomenclature of Carbohydrates](https://iupac.qmul.ac.uk/2carb/index.html) (Recommendations 1996); more specifically, 

[**Section 2-Carb-19. Alditols**](https://iupac.qmul.ac.uk/2carb/19.html)

> Alditols are named by changing the suffix '-ose' in the name of the corresponding aldose into '-itol'.

Since arabinitol can be formed by the reduction of either arabinose or lyxose, it could be also named "lyxitol" and indeed, this latter synonym exists. [CHEBI:18333](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18333) has synonym "D-Lyxitol" and [CHEBI:18403](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18403) has synonym "L-lyxitol". I suggest adding the term "lyxitol" as a synonym to [CHEBI:22605](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:22605). However, "lyxitol" is not a recommended name. IUPAC says:

> If the same alditol can be derived from either of two different aldoses, or from an aldose or a ketose, preference is ruled by [2-Carb-2.1](https://iupac.qmul.ac.uk/2carb/02.html#021) or [2-Carb-2.2.2](https://iupac.qmul.ac.uk/2carb/02.html#0222) as appropriate.

In this particular case, the rules applied are:

> **2.1.3.** The parent with the name that comes first in an alphabetical listing based on:
>
> **2.1.3.1.** the trivial name or the configurational prefix(es) of the systematic name, e.g. allose rather than glucose, a _gluco_ rather than a _gulo_ derivative;

and

> **2-Carb-2.2.2. Choice of parent name**
>
> The name selected is that which comes first in the alphabet (configurational prefixes included). 

This is also confirmed in the New Blue Book, P-102.5.6.5.1: 
> Choice of a parent structure:
> <small>D</small>-arabinitol (not <small>D</small>-lyxitol)

Please add the formula C5H12O5 to pentitol ([CHEBI:25899](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25899)). I don't think there exists an enantiomeric unspecific SMILES just for arabinitol but it does exist for pentitol ([CHEBI:25899](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25899)): C(C(C(C(CO)O)O)O)O

I also suggest adding the completely systematic IUPAC names (as IUPAC synonyms):

(2*R*,4*R*)-pentane-1,2,3,4,5-pentol for D-arabinitol ([CHEBI:18333](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18333))
(2*S*,4*S*)-pentane-1,2,3,4,5-pentol for L-arabinitol ([CHEBI:18403](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18403)) 
*rel*-(2*R*,4*R*)-pentane-1,2,3,4,5-pentol for arabinitol ([CHEBI:22605](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:22605))
pentane-1,2,3,4,5-pentol for pentitol ([CHEBI:25899](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25899))

**Comment by K-r-ll** [comment]
Also, for aesthetic reasons, I suggest to redraw the main diagrams for D-arabinitol ([CHEBI:18333](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18333)) and L-arabinitol ([CHEBI:18403](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18403)) to have them in the same (horizontal) orientation as other pentitols, ribitol ([CHEBI:15963](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15963)) and xylitol ([CHEBI:17151](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17151)), as well as their corresponding aldehyde parents, *aldehydo*-D-arabinose ([CHEBI:46983](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:46983)) and *aldehydo*-L-arabinose ([CHEBI:6182](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:6182)). That will make all of them easily comparable by eye.

**Comment by sorenwacker** [comment]
Thanks for the resources! I not a chemists, so I find this very helpful. If I may pick your brain on the my confusion formulated above? Do you have any insights where Arabitol comes from? Is it a historic name?

Regarding the naming and the enantiomeric unspecific structures: both were explained in #4338. I am very much insterested in the enantionmeric unspecific SMILES string and a nice human readable name as a reference for a metabolomics application.

**Comment by sorenwacker** [comment]
I also think the enantiomeric unspecific ChEBI entries should have a smiles string. For metabolomics, I would reference that structure, and the Metabolights (also from EMBL) database can then go an pull the SMILES string to generate an image. So, the tools would be integrated even better.

**Comment by K-r-ll** [comment]
I am not quite sure how the terms "arabinol" and "arabitol" came about. I suppose they are fruits of the process that linguists call [clipping](https://en.wikipedia.org/wiki/Clipping_(morphology)): it's like when we say "exam" instead of "examination". The word "arabinitol" is just a bit too long.

D-arabinitol ([CHEBI:18333](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18333)) contains D-arabinol and D-arabitol as synonyms; likewise L-arabinitol ([CHEBI:18403](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18403)) has synonyms L-arabinol and L-arabitol. This is not a problem. What we (rightly) may find confusing is that the term "arabitol" is used when referring specifically to its D enantiomer, as in Wikipedia article on [Arabitol](https://en.wikipedia.org/wiki/Arabitol). Unfortunately this is way too common in the world of carbohydrates: when they say "glucose" they (usually) mean "D-glucose" rather than "either D- or L-glucose" or "racemic mixture of D- and L-glucose". We have to live with that; that's why (IMHO) we need unambiguous ChEBI names.
