### ISSUE TITLE
hippurate needs formula, smiles, IUPAC, mass etc.

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4361]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:132966

**Comment by amalik01** [comment]
This specific entry is for a class of compounds so therefore no formula, smiles is provided.
If you want the more specific entry, then its CHEBI:606565 which has the synonym 'hippurate'.

In ChEBI, we have individual compounds aswell as classes of compounds. For example benzene (CHEBI:16716) is a specific compound whereas benzenes (CHEBI:22712) is a class of compounds containing the benzene core structure.

**Comment by sorenwacker** [comment]
I didn't know hippurate is a group of compounds. I thought it is a specific structure. So, then hippurate is a group, but also the synonym of a specific structure? Seems most of the chemical sources speak of hippurate as a specific structure.

I think, a flag about the entry type would be good in the obo graph that indicates whether the entry is a specific structure, a racemic mixture, or a group of comounds. 

I have seen other entries for groups, and they often contained the scaffold of the group with R-groups. Has that policy changed in the recent versions of ChEBI?

**Comment by amalik01** [comment]
You're right, most sources will refer to hippurate as a specific compound which is CHEBI:606565. However, the previous ChEBI curator has created a class called hippurate (CHEBI:132966) to group together all derivatives of this compound. For example p-aminohippurate (ChEBI:64703) also belongs to this class since its name has the word 'hippurate' in it.

Grouping compounds in this way is common in ChEBI, for example phenol (CHEBI:15882) is a specific compound which belongs to the class called phenols (CHEBI:33853). 

To avoid confusion, i have renamed CHEBI:132966 as hippurates (plural) instead of hippurate. I think the overall aim of the previous curator was to group compounds such as 2-iodohippurate, p-hydroxyhippurate etc under this class.

**Comment by sorenwacker** [comment]
And does that mean the groups with R- groups are outdated?

**Comment by amalik01** [comment]
We still use R-groups for certain compound classes. For this specific class, the variation in substitution is large so we currently don't include a structure. In the future, we may add a markush structure (https://en.wikipedia.org/wiki/Markush_structure) to such classes.
