### ISSUE TITLE
Roles should not have SMILES or Formula as they are not molecular entities

### ISSUE THREAD

**Issue by JervenBolleman** [ebi-chebi/ChEBI#4477]
This leads to confusion e.g. [CHEBI:13193](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:13193). 

As an aside it would be nice if there was a chebi "Hydrogen accepting molecular entity" that is a child term of [CHEBI:23367](https://www.ebi.ac.uk/chebi/chebiOntology.do?treeView=true&chebiId=CHEBI:23367) which has the role [CHEBI:13193](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:13193).

**Comment by cmungall** [comment]
It looks like this was fixed in one place but no systematic check was put in place.

Some dubious properties assigned to roles

CHEBI:13193|hydrogen acceptor|obo:chebi/formula|R
CHEBI:13193|hydrogen acceptor|obo:chebi/smiles|*
CHEBI:156295|G-15|obo:chebi/charge|0
CHEBI:156295|G-15|obo:chebi/formula|C19H16BrNO2
CHEBI:156295|G-15|obo:chebi/inchi|InChI=1S/C19H16BrNO2/c20-15-9-18-17(22-10-23-18)8-14(15)19-13-6-3-5-11(13)12-4-1-2-7-16(12)21-19/h1-5,7-9,11,13,19,21H,6,10H2/t11-,13-,19-/m1/s1
CHEBI:156295|G-15|obo:chebi/inchikey|YOLTZIVRJAPVPH-MJCKAROISA-N
CHEBI:156295|G-15|obo:chebi/mass|370.246
CHEBI:156295|G-15|obo:chebi/monoisotopicmass|369.03644
CHEBI:156295|G-15|obo:chebi/smiles|BrC=1C([C@@]2(N(C=3C([C@@]4([C@]2(C(C(=C4[H])[H])([H])[H])[H])[H])=C(C(=C(C3[H])[H])[H])[H])[H])[H])=C(C=5OC(OC5C1[H])([H])[H])[H]
CHEBI:156296|G-1|obo:chebi/charge|0
CHEBI:156296|G-1|obo:chebi/formula|C21H18BrNO3
CHEBI:156296|G-1|obo:chebi/inchi|InChI=1S/C21H18BrNO3/c1-11(24)12-5-6-18-15(7-12)13-3-2-4-14(13)21(23-18)16-8-19-20(9-17(16)22)26-10-25-19/h2-3,5-9,13-14,21,23H,4,10H2,1H3/t13-,14+,21-/m1/s1
CHEBI:156296|G-1|obo:chebi/inchikey|VHSVKVWHYFBIFJ-HKZYLEAXSA-N
CHEBI:156296|G-1|obo:chebi/mass|412.283
CHEBI:156296|G-1|obo:chebi/monoisotopicmass|411.04701
CHEBI:156296|G-1|obo:chebi/smiles|BrC=1C([C@@]2(N(C3=C([C@]4([C@@]2(C(C(=C4[H])[H])([H])[H])[H])[H])C(=C(C(=C3[H])[H])C(=O)C([H])([H])[H])[H])[H])[H])=C(C=5OC(OC5C1[H])([H])[H])[H]
CHEBI:17499|hydrogen donor|obo:chebi/charge|0
CHEBI:17499|hydrogen donor|obo:chebi/formula|RH2
CHEBI:17499|hydrogen donor|obo:chebi/mass|2.016
CHEBI:17499|hydrogen donor|obo:chebi/monoisotopicmass|2.01565
CHEBI:17499|hydrogen donor|obo:chebi/smiles|*([H])[H]
CHEBI:190676|HA Binder_mPEP35|obo:chebi/charge|+10
CHEBI:190676|HA Binder_mPEP35|obo:chebi/formula|C159H298N48O35S
CHEBI:190676|HA Binder_mPEP35|obo:chebi/inchi|InChI=1S/C159H288N48O35S/c1-24-93(22)128(206-142(226)103(52-34-42-70-167)181-138(222)107(59-61-118(168)210)187-131(215)97(46-28-36-64-161)183-143(227)109(73-83(2)3)179-121(213)56-26-25-55-117-129-116(81-243-117)199-159(242)207-129)155(239)192-101(50-32-40-68-165)136(220)196-113(77-95-79-175-82-178-95)147(231)202-126(91(18)19)153(237)203-123(88(12)13)150(234)190-99(48-30-38-66-163)134(218)193-110(74-84(4)5)144(228)184-102(51-33-41-69-166)141(225)200-125(90(16)17)152(236)205-127(92(20)21)154(238)204-124(89(14)15)151(235)191-100(49-31-39-67-164)135(219)194-111(75-85(6)7)145(229)185-105(54-44-72-177-158(173)174)137(221)198-115(80-208)148(232)188-108(60-62-119(169)211)139(223)195-112(76-86(8)9)146(230)201-122(87(10)11)149(233)189-98(47-29-37-65-162)132(216)182-104(53-43-71-176-157(171)172)133(217)180-96(45-27-35-63-160)130(214)186-106(58-57-94(23)209)140(224)197-114(156(240)241)78-120(170)212/h79,82-93,96-117,122-129,208H,24-78,80-81,160-167H2,1-23H3,(H2,168,210)(H2,169,211)(H2,170,212)(H,175,178)(H,179,213)(H,180,217)(H,181,222)(H,182,216)(H,183,227)(H,184,228)(H,185,229)(H,186,214)(H,187,215)(H,188,232)(H,189,233)(H,190,234)(H,191,235)(H,192,239)(H,193,218)(H,194,219)(H,195,223)(H,196,220)(H,197,224)(H,198,221)(H,200,225)(H,201,230)(H,202,231)(H,203,237)(H,204,238)(H,205,236)(H,206,226)(H,240,241)(H4,171,172,176)(H4,173,174,177)(H2,199,207,242)/p+10/t93-,96-,97-,98-,99-,100-,101-,102-,103-,104-,105-,106-,107?,108-,109-,110-,111-,112-,113-,114-,115-,116+,117?,122-,123-,124-,125-,126-,127-,128-,129+/m0/s1
CHEBI:190676|HA Binder_mPEP35|obo:chebi/inchikey|QMKNKHMYTQVEAI-QNPBOAAUSA-X
CHEBI:190676|HA Binder_mPEP35|obo:chebi/mass|3474.490
CHEBI:190676|HA Binder_mPEP35|obo:chebi/monoisotopicmass|3472.26801
CHEBI:190676|HA Binder_mPEP35|obo:chebi/smiles|[NH2+]([C@H](C(N[C@H](C(NC(C(N[C@H](C(N[C@H](C(N[C@H](C(=O)N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(N[C@H](C(=O)[O-])CC(N)=O)=O)CCC(C)=O)=O)CCCC[NH3+])=O)CCCNC(N)=[NH2+])=O)CCCC[NH3+])=O)C(C)C)=O)CC(C)C)=O)CCC(=O)N)=O)CO)=O)CCCNC(N)=[NH2+])=O)CC(C)C)=O)CCCC[NH3+])=O)C(C)C)=O)C(C)C)=O)C(C)C)=O)CCCC[NH3+])=O)CC(C)C)=O)CCCC[NH3+])=O)C(C)C)=O)C(C)C)=O)CC1=CNC=N1)CCCC[NH3+])=O)[C@H](CC)C)=O)CCCC[NH3+])=O)CCC(=O)N)=O)CCCC[NH3+])=O)CC(C)C)C(CCCC[C@@H]2[C@]3([C@@](CS2)(NC(N3)=O)[H])[H])=O
CHEBI:195299|Grace_C1_2023|obo:chebi/charge|0
CHEBI:195299|Grace_C1_2023|obo:chebi/formula|C25H26FN3O8
CHEBI:195299|Grace_C1_2023|obo:chebi/inchi|InChI=1S/C25H26FN3O8/c1-16(30)36-22-5-3-2-4-19(22)24(32)35-15-23(31)27-13-18-14-29(25(33)37-18)17-6-7-21(20(26)12-17)28-8-10-34-11-9-28/h2-7,12,18H,8-11,13-15H2,1H3,(H,27,31)
CHEBI:195299|Grace_C1_2023|obo:chebi/inchikey|DHNOULBSVABTDJ-UHFFFAOYSA-N
CHEBI:195299|Grace_C1_2023|obo:chebi/mass|515.494
CHEBI:195299|Grace_C1_2023|obo:chebi/monoisotopicmass|515.17039
CHEBI:228251|PNU-74654|obo:chebi/charge|0
CHEBI:228251|PNU-74654|obo:chebi/formula|C19H16N2O3
CHEBI:228251|PNU-74654|obo:chebi/inchi|InChI=1S/C19H16N2O3/c1-14-11-12-16(23-14)13-20-21-19(22)17-9-5-6-10-18(17)24-15-7-3-2-4-8-15/h2-13H,1H3,(H,21,22)/b20-13+
CHEBI:228251|PNU-74654|obo:chebi/inchikey|JJEDWBQZCRESJL-DEDYPNTBSA-N
CHEBI:228251|PNU-74654|obo:chebi/mass|320.348
CHEBI:228251|PNU-74654|obo:chebi/monoisotopicmass|320.11609
CHEBI:228251|PNU-74654|obo:chebi/smiles|CC1=CC=C(O1)\C=N\NC(=O)C1=C(OC2=CC=CC=C2)C=CC=C1
