### ISSUE TITLE
Ontology recommendations

### ISSUE THREAD

**Issue by eriksson1800** [ebi-chebi/ChEBI#4484]
Here are a few recommendations my team and I have proposed for the CHEBI ontology:

- benzopyrroles (`22728`) should be a subclass of `pyrroles` (`26455`)
- Entities that are subclasses of `group` and `molecular entity`: 144321, 156504, 74635, 167175, 167174, 167178
64898		
- `anionic amino-acid residue` should be a subclass of `amino acid residue` (33708)

**Comment by amalik01** [comment]
Hi,
Benzopyrroles cannot be classified as pyrroles since they are bicyclic compounds whereas pyrroles are monocyclic. A different type of relationship will need to be added to ChEBI to capture this type of relationship (For example _has_substructure_ pyrolle). 

I have fixed the above entries that were in two hierarchies (group and molecular entity).

I have added a conjugate acid/base relationship to capture the relation between amino acid residue and anion amino-acid residue.
