### ISSUE TITLE
Wrong class descriptions

### ISSUE THREAD

**Issue by eriksson1800** [ebi-chebi/ChEBI#4485]
Here are a few incorrect class description my team and I have stumbled across:

- `35990`	wrong description, because bridged compounds have at least three atoms in common (otherwise fused compounds would be a part of bridged compounds) as described here [[1]](https://en.wikipedia.org/wiki/Bicyclic_molecule) 
- `36683`	organochlorine compound SMILES `*Cl`, should have `[*]CCl`
- `65285` 	aliphatic amide - picture only matches primary amides (also residue too unspecific, but that is not easily solvable)

**Comment by amalik01** [comment]
Hi,
There is nothing wrong with the definition in ChEBI for bridged compounds since we are referring to the common atoms between the two rings (also known as the bridgehead atoms). See image below which describes the difference between a bridged compound and a fused compound:

![image](https://github.com/ebi-chebi/ChEBI/assets/41328040/bbb7b2da-ff88-4a22-a91b-9190a73cd993)

The Wikipedia definition is also fine since they are not referring to the common atoms and instead mention the bridge which needs 3 or more atoms.

The SMILES are generated automatically based on the chemical structure input. The SMILES for organochlorine compound has now been regenerated as Cl[*]. The symbol * is treated by SMILES as a valid atomic symbol meaning 'unspecified atomic number'. There is nothing I can do to make sure that R contains at least one carbon atom since we do not have the ability to edit the SMILES in the curator tool. 

I will try and fix the structure or ChEBI name of aliphatic amide (CHEBI:65285) after informing the submitter who deposited this entry to ChEBI.

Thanks

**Comment by amalik01** [comment]
I have updated the definition of bridged compound so that it is clear to the user.
