### ISSUE TITLE
oganesson lacks a formula

### ISSUE THREAD

**Issue by cmungall** [ebi-chebi/ChEBI#4490]
I am using chemrof to classify all CHEBI classes into distinct metaclasses.

for chemrof ChemicalElement, I noticed a discrepancy - it's the only element in CHEBI that lacks a formula. This should be `Og` to be consistent will all other elements

**Comment by amalik01** [comment]
Hi Chris,

We are aware of this issue and it has been fixed in ChEBI 2 (the beta version will be made available in the next few months). The formula has been marked to deleted in the current ChEBI since the version of Ketcher (the structure editor) that is being used is outdated and the periodic table of the structure editor lacks the Og atom. Our curator tool therefore doesn't recognize this new atom.

![image](https://github.com/ebi-chebi/ChEBI/assets/41328040/9419f6b2-4d87-410b-abdd-2129418daa1b)
