### ISSUE TITLE
Reverse order of unspecified vs specified chirality.

### ISSUE THREAD

**Issue by sorenwacker** [ebi-chebi/ChEBI#4511]
<img width="462" alt="image" src="https://github.com/ebi-chebi/ChEBI/assets/3391614/1588e4c5-9fde-4fea-9fa9-8b41f5553ab6">

**Comment by sorenwacker** [comment]
Shouldn't (R)-mevalonate be a specification of mevalonate? The way I see it is that mevalonate is the larger category which should include both (R)-mevalonate and (S)-mevalonate.

**Comment by amalik01** [comment]
@sorenwacker  

I'm not sure how you generated the ontology graph since its not right. There is no **is a** relationship between mevalonate (CHEBI:25350) and (R)-mevalonate (CHEBI:36464).

mevalonate is a racemate and has_part (R)-mevalonate and has_part (S)-mevalonate.

![image](https://github.com/user-attachments/assets/2ca87cd6-7ef6-465a-aa23-7ddcfc6ced9e)

**Comment by sorenwacker** [comment]
Oh, that's right. I added all edges as IS_A.
