### ISSUE TITLE
Image description of molecules changes for different sizes

### ISSUE THREAD

**Issue by sfluegel05** [ebi-chebi/ChEBI#4517]
On the ChEBI website, I have noticed some discrepancies between the "normal size" image description of molecules and the "zoomed in" image description. For instance, `Alanyl-alanine` looks like this in normal size:
![grafik](https://github.com/user-attachments/assets/0289427e-62d5-4b44-8981-6f36a72a0ee0)
but changes to this image when zooming in:
![grafik](https://github.com/user-attachments/assets/bb5672db-8c9e-4006-a9e7-840546b059a9)
Note that the "crossed-lines" double bond has become a "parallel-lines" double bond.

Another example would be isotabtoxin (although the differences there are minor).

**Comment by amalik01** [comment]
I have fixed the structure.

We are aware of this issue and this issue mostly likely arises because of indigo, a toolkit that we use in ChEBI which renders structures from text format into images and it doesn't seem to do a good job in some cases. We are currently redeveloping ChEBI and will no longer be using this toolkit.
